import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import NoSSRWrapper from "@/components/NoSSRWrapper";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "URL Redirector",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NoSSRWrapper>
      <html lang="en" className="">
        <body
          className={cn(
            "min-h-screen max-w-screen overflow-x-hidden bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          {children}
          <Toaster position="bottom-left" richColors />
        </body>
      </html>
    </NoSSRWrapper>
  );
}
